---
title: Endless ERA Gaming
timezone: UTC
collections:
  creators:
    title: Creators
    output: true
  posts:
    title: Posts
    output: true
  store:
    title: Store
    output: true
    sort_by: date
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
page_gen-dirs: true
page_gen:
- data: ContentCreators
  template: creator
  name: name
  dir: creators
theme: 
plugins:
- jekyll-feed
- jekyll-datapage-generator
